// Package contractport generates transport-independent unary module ports.
package contractport

import (
	"google.golang.org/protobuf/compiler/protogen"
)

var (
	contextPackage = protogen.GoImportPath("context")
	errsPackage    = protogen.GoImportPath("github.com/wplbyx/modular/packages/errs")
)

// Generate emits one *_modular.pb.go file beside each generated protobuf file.
func Generate(plugin *protogen.Plugin) error {
	for _, file := range plugin.Files {
		if !file.Generate {
			continue
		}
		generateFile(plugin, file)
	}
	return nil
}

func generateFile(plugin *protogen.Plugin, file *protogen.File) {
	services := make([]*protogen.Service, 0, len(file.Services))
	for _, service := range file.Services {
		for _, method := range service.Methods {
			if !method.Desc.IsStreamingClient() && !method.Desc.IsStreamingServer() {
				services = append(services, service)
				break
			}
		}
	}
	if len(services) == 0 {
		return
	}

	generated := plugin.NewGeneratedFile(file.GeneratedFilenamePrefix+"_modular.pb.go", file.GoImportPath)
	generated.P("// Code generated by protoc-gen-go-modular. DO NOT EDIT.")
	generated.P()
	generated.P("package ", file.GoPackageName)
	generated.P()
	for _, service := range services {
		generateService(generated, service)
	}
}

func generateService(generated *protogen.GeneratedFile, service *protogen.Service) {
	portName := service.GoName + "Port"
	remoteName := "remote" + service.GoName
	generated.P("// ", portName, " is the transport-independent unary contract for ", service.GoName, ".")
	generated.P("// Requests are read-only for the duration of a call and must not be retained by implementations.")
	generated.P("type ", portName, " interface {")
	for _, method := range service.Methods {
		if method.Desc.IsStreamingClient() || method.Desc.IsStreamingServer() {
			continue
		}
		generated.P(
			method.GoName,
			"(ctx ", generated.QualifiedGoIdent(contextPackage.Ident("Context")),
			", in *", generated.QualifiedGoIdent(method.Input.GoIdent),
			") (*", generated.QualifiedGoIdent(method.Output.GoIdent), ", error)",
		)
	}
	generated.P("}")
	generated.P()
	generated.P("type ", remoteName, " struct { client ", service.GoName, "Client }")
	generated.P()
	generated.P("// NewRemote", service.GoName, " adapts the standard gRPC client to ", portName, ".")
	generated.P("func NewRemote", service.GoName, "(client ", service.GoName, "Client) ", portName, " {")
	generated.P("return &", remoteName, "{client: client}")
	generated.P("}")
	generated.P()
	for _, method := range service.Methods {
		if method.Desc.IsStreamingClient() || method.Desc.IsStreamingServer() {
			continue
		}
		generated.P(
			"func (remote *", remoteName, ") ", method.GoName,
			"(ctx ", generated.QualifiedGoIdent(contextPackage.Ident("Context")),
			", in *", generated.QualifiedGoIdent(method.Input.GoIdent),
			") (*", generated.QualifiedGoIdent(method.Output.GoIdent), ", error) {",
		)
		generated.P("reply, err := remote.client.", method.GoName, "(ctx, in)")
		generated.P("if err != nil { return nil, ", generated.QualifiedGoIdent(errsPackage.Ident("FromError")), "(err) }")
		generated.P("return reply, nil")
		generated.P("}")
		generated.P()
	}
	generated.P("var _ ", portName, " = (*", remoteName, ")(nil)")
	generated.P()
}
